# Generated by Django 4.0.1 on 2022-01-16 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_post_tipopost_alter_post_posteador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='actualizacion',
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
