# Generated by Django 4.0.1 on 2022-01-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_post_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/NoPublicado'),
        ),
    ]
