# Generated by Django 4.0.1 on 2022-01-16 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_post_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tematica',
        ),
        migrations.AddField(
            model_name='post',
            name='tematica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserApp.tematica'),
            preserve_default=False,
        ),
    ]
