# Generated by Django 4.0.1 on 2022-01-18 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariospost',
            name='comentarista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarista', to=settings.AUTH_USER_MODEL),
        ),
    ]
