# Generated by Django 4.0.1 on 2022-02-04 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0010_perfil_alter_likes_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserApp.avatar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
