# Generated by Django 4.0.1 on 2022-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_perfil_avatar_perfil_biografia_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagenPost',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
