# Generated by Django 4.0.1 on 2022-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_post_imagenpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagenPost',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagenes'),
        ),
    ]
