# Generated by Django 4.0.1 on 2022-02-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='profileImageDefault.jpg', null=True, upload_to='avatares'),
        ),
    ]
