# Generated by Django 4.0.1 on 2022-02-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_alter_avatar_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar',
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagenPerfil',
            field=models.ImageField(blank=True, default='PorDefecto/profileImageDefault.jpg', null=True, upload_to='avatares'),
        ),
    ]
