# Generated by Django 4.0.1 on 2022-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_postfavoritos_delete_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
