# Generated by Django 4.0.1 on 2022-02-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_mismensajes_destinatario_alter_mismensajes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mismensajes',
            name='room',
        ),
    ]
