# Generated by Django 4.0.1 on 2022-02-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0024_remove_mismensajes_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lenguaje',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='vistadelpost',
            name='post',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='VistaDelPost',
        ),
    ]
